### PR TITLE
add support for local dictionaries

### PR DESCRIPTION
**Pull request by kortschak**
Updates #3.

### CODE REVIEW

**Comment by philpennock** [comment]
Thanks!  So, I tried it and at first it didn't work; tracked it down to the content size hint being mandatory in the `.words` file, unlike in `~/.hunspell_en_US`; it looks as though in the Hunspell source, `src/tools/hunspell.cxx` uses `load_privdic()` which just reads the lines and loads the words one-by-one, instead of those files being `.dic` format.

At which point it's a philosophy issue around naming, extensions, and if these should be edited by humans or not.

**Comment by kortschak** [comment]
When I was testing this, is was working for me. Can you share what environment you are working in? The method I am loading private directories with is
```
/* load extra dictionaries (only dic files)
 * output: 0 = additional dictionary slots available, 1 = slots are now full*/
LIBHUNSPELL_DLL_EXPORTED int Hunspell_add_dic(Hunhandle* pHunspell,
                                              const char* dpath);
```
Addressing #2 is not a goal for this PR.

**Comment by philpennock** [comment]
For clarity:
 * I have a `~/.hunspell_en_US` file, it's not used, I didn't expect it to be used
 * I expected that a ".words" file for maintenance by humans would just be a list of words, just like `~/.hunspell_en_US`
 * Once I added a size hint, the `.words` file in the same directory as `go.mod` was used and the results are great, thank you!
 * So I think there's a philosophy issue here and whether or not the .words files should be edited by humans should be called out, or at least "include a size hint on the first line, 0 will do".

Sorry for being too terse to be clear before.

**Comment by kortschak** [comment]
No worries. I think that the `.words` file should be considered to be human editable and that adequate documentation about the requirements of the `.words` file is enough, I'll try to sort out some reasonable phrasing and add that. The work flow that I imagined was that you run the spell check, it generates the `.word` file and you go through and vet it for words that you agree with, deleting those you don't (the size hint does not need to change). This is then committed to the repo and used for spell checking.

**Comment by kortschak** [comment]
@philpennock Please take a look at the current phrasing.

**Comment by philpennock** [comment]
LGTM

**Comment by kortschak** [comment]
I modified this slightly so that it is possible to update the `.words` file with new words. This improves the ergonomics.

**Pull request merged**
