### PR TITLE
allow words found in license files to be added to dictionary

### LINKED ISSUE #13: teach the tool about copyright lines
I keep seeing warnings of the form:

```
/home/mvdan/src/sh/shell/doc.go:1:1: "Martí" is misspelled in comment
/home/mvdan/src/sh/shell/doc.go:1:1: "mvdan" is misspelled in comment
	Copyright (c) 2017, Daniel Martí <mvdan@mvdan.cc>
```

Presumably I shouldn't need to add my username or full name to a `.words` file in every project :) It should be fairly easy to discard a comment if it looks like a copyright line. Another route would be to ignore `Full Name <email@domain.com>`.

### PR DESCRIPTION
**Pull request by kortschak**
Closes #13.

/cc @mvdan

### CODE REVIEW

**Comment by mvdan** [comment]
A bit late, but SGTM! This would pick up my name and email address in most personal projects, solving the copyright lines for those.

It wouldn't quite work for larger projects where I went for an AUTHORS or CONTRIBUTORS file, akin to what the Go project does. See https://github.com/burrowers/garble/blob/master/LICENSE and https://github.com/burrowers/garble/blob/master/AUTHORS, for example.

**Comment by kortschak** [comment]
Yeah. I thought about AUTHORS/CONTRIBUTORS but while that approach is used by some, it's not formalised well enough to make it safe. I am thinking about making it possible to obtain the list of contributors from `git shortlog -s`. This could be probed without error and added if possible.

**Comment by mvdan** [comment]
I also thought about using the git history, but note that that will result in different results when the source code is used without the git data. This is the case with downloaded Go modules, as a zip is downloaded and extracted. So if I did `cd main-project && gospel some-dependency/...`, it could be different than `git clone https://[...]/some-dependency && cd some-dependency && gospel ./...`.

**Comment by kortschak** [comment]
Yes, this is the concern that I also had. I'm less worried about that since spell checking would most likely be done in a git repository since the zip will not be upstreamable. It is a limitation that is reasonable and can be covered by documentation.

**Comment by mvdan** [comment]
"You would only spell check if you are developing, in which case you're in a VCS clone" is fair enough, but like you say, needs to be documented :)

FYI, if you go with that route, I would almost say that you don't need to bother looking at LICENSE files. I can't think of a situation where a special word would be present in a license file but not in the git log.

**Comment by kortschak** [comment]
The project name may well not be in the output of shortlog -se. Many project match the project name into import paths, but some don't.

**Comment by kortschak** [comment]
Turns out `git shortlog` behaves weirdly. I am unable to capture the stdout from it (works fine with `git log`).

**Pull request merged**
